Use stable nvidia container toolkit
NVIDIA/nvkind pull request #21
Opened 2024-12-17 15:08 UTC by p11o

This fixes an issue with the bitnami postgres helm chart.  I noticed that simply installing the experimental package caused postgres to fail. I wasn't able to figure out why :disappointed: 

Steps to reproduce the issue:

```bash
nvkind cluster create
helm install pg oci://registry-1.docker.io/bitnamicharts/postgresql
watch kubectl get pods
# wait 5 minutes to see postgres pod restart / crashloopbackoff
```

I'm not sure if this is the correct way to fix this, but it may at least save others some time.

2024-12-17 15:15 UTC, klueska commented
@elezar should we still be pulling from these repos at all or should we be pulling from the cuda downloads repo?

2025-01-09 08:46 UTC, elezar commented
> @elezar should we still be pulling from these repos at all or should we be pulling from the cuda downloads repo?

I would recommend using our existing repos here as they are simpler to configure programatically.

2025-01-09 08:47 UTC, elezar submitted a review, later dismissed
Thanks @p11o

2025-01-09 08:48 UTC, elezar requested changes
Thanks @p11o

The changes look good, but please sign-off your commit. We still need to enable DCO checks on this repo.

2025-01-09 11:36 UTC, p11o commented
Whoops sorry about that :facepalm:.  Should be all set now.

2025-02-13 11:05 UTC, elezar commented
Sorry @p11o. I missed re-reviewing this before working with @jgehrcke on #26 (which also includes these fixes).

2025-02-13 11:05 UTC, closed without merging